### ISSUE TITLE
Trip not optimized on Operator Dashboard - Operator Dashboard 

### ISSUE THREAD

**Issue by thelulaloop** [LULA-LOOP/.github#24] opened 2024-09-11 14:54 UTC
Add a title
Trip not optimized on Operator Dashboard
Current Behaviour 
When the operator(EYONA) assigned trips for commuters who lives in the same street(3 elm street grassy park and 1 elm street grassy park), the system does not group them in one vehicle but rather split them in two vehicles.
Expected Behaviour 
The system supposed to create the trip in a most optimized way having the 3 commuters living in the same street to be in one vehicle.
Steps to Reproduce
1. Logged into EYONA operator dashboard
2.Go to Bookings - on today's bookings
3. Clicked on the Amplify5 : Southern Suburbs (Ottery/Wynberg/GP & Surroundings) - ORANGE
4. Observed that all the 3 commuters have been splited into two trips: Yusuf Davids
3 Elm Street, Grassy Park, Western Cape 7941, South Africa ; Kyle Newton
1 Elm Street, Grassy Park, Western Cape 7941, South Africa and Moegamat Zubair Samodien
3 Elm Street, Grassy Park, Western Cape 7941, South Africa
Reproduction Link
https://operator.lulaloop.co.za/loops/1538/schedule-trips/673741
Additional Information
When a commuter is removed from a trip, it cancels the booking of the commuter instead of removing the the booking from a specific trip.
What platform is this issue being experienced on?
Operator Dashboard
Bug submitted by: @Larissa Mawonde

**Comment by thelulaloop** [comment] 2024-09-12 08:20
@ArseneMwenze please have a look before the team does?

**Comment by ArseneMwenze** [comment] 2024-09-13 10:08
Noted. Thank you

**Comment by ArseneMwenze** [comment] 2024-09-17 11:35
Hi @thelulaloop ,
I have tested on my side and I can't replicate the issue.

As per screen recording below :

1. I have created 15 commuters with the same addresses than the ones on that Amplify5 loop.
2. I have made bookings for all 15 commuters on a single schedule.
3. I created trips of 5 and assigned them to 3 different drivers.
4. The commuters with the addresses mentioned on the bug happened to all be grouped together and assigned to the same vehicle.

**Comment by ArseneMwenze** [comment] 2024-09-17 11:35
https://github.com/user-attachments/assets/9ca83cbb-d825-4a8a-82b1-e16906cfd1b7

**Comment by evidencefrank** [comment] 2024-11-29 04:33
Moving the ticket to testing. Issue can't be reproduced.

**Comment by xabiso-nordy** [comment] 2024-12-03 09:58
@evidencefrank I think we should close if we can't reproduce it, and @ArseneMwenze also can't reproduce it

**Closed as completed** 2024-12-04 08:32 UTC
